# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ginkit

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ incpatch .Version }}-next"

report_sizes: true

builds:
  - skip: true

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs'
      - 'CICD'
      - 'typo'
  groups:
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "Others"
      order: 999

release:
  name_template: "v{{ .Version }}"
